// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace jwldnr.VisualLinter
{
    internal sealed partial class Vsix
    {
        public const string Id = "21d9f99b-ec42-4df4-8b16-2a62db5392a5";
        public const string Name = "VisualLinter";
        public const string Description = @"Visual Studio JavaScript linter using ESLint.";
        public const string Language = "en-US";
        public const string Version = "1.1.0";
        public const string Author = "Jean Alexander Woldner";
        public const string Tags = "Visual Studio, Visual Studio 2015, Visual Studio 2017, Visual Studio 2019, Lint, Linter, Linting, ESLint, JavaScript, TypeScript";
    }
}
