// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace jwldnr.VisualLinter
{
    static class Vsix
    {
        public const string Id = "832aee43-88e1-4e51-ac31-d412d356dfdf";
        public const string Name = "VisualLinter";
        public const string Description = @"Visual Studio Linter using ESLint (installed globally) with visual feedback in the text buffer.";
        public const string Language = "en-US";
        public const string Version = "0.2.13";
        public const string Author = "Jean Alexander Woldner";
        public const string Tags = "";
    }
}
