// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace jwldnr.VisualLinter
{
    static class Vsix
    {
        public const string Id = "21d9f99b-ec42-4df4-8b16-2a62db5392a5";
        public const string Name = "VisualLinter";
        public const string Description = @"Visual Studio JavaScript linter using ESLint.";
        public const string Language = "en-US";
        public const string Version = "1.0.62";
        public const string Author = "Jean Alexander Woldner";
        public const string Tags = "Visual Studio, visual studio 2017, lint, linter, Linting, ESLint, Javascript";
    }
}
